### ISSUE TITLE
Bun + Typescript

### ISSUE THREAD

**Issue by reyamir** [Yonle/bostr#14]
こんにちは,
I'm intend to contribute to bostr by migrate it to Bun + Typescript. But I not sure you have plan for it or not?, if you want to migrate it, I can create a PR

Websocket in Bun is 7x faster than Node: https://bun.sh/docs/api/websockets

**Comment by reyamir** [comment]
Look like we cannot fully migrate to Bun until this feature is implemented https://github.com/oven-sh/bun/issues/2428

**Comment by Yonle** [comment]
> こんにちは
Hello.

> I'm intend to contribute to bostr by migrate it to Bun + Typescript. But I not sure you have plan for it or not?

I have no plan for porting these codes into Typescript. In fact i have no skill to write code in TS nor even planned to do so.

I will just keep it with NodeJS. I have no plan for migrating it to something similiar like Deno or Bun due to unavailability on certain platforms that i use (Notably: Android, OpenBSD).

> Websocket in Bun is 7x faster than Node: https://bun.sh/docs/api/websockets

I do not fully support or even believe in Bun words. Sure, it may be faster than Node, however could it check and broadcast events even faster than the current one did? As of now, The current performance is already fair as far as i could tell.

> Look like we cannot fully migrate to Bun until this feature is implemented oven-sh/bun#2428

I do not plan to migrate this project into anything else. `clusters` is not really needed, You could just remove it and it will work exactly the same.
