### ISSUE TITLE
Received events exceed limit

### ISSUE THREAD

**Issue by dluvian** [Yonle/bostr#20]
I have started to close connections to "spammy" relays in my client. If a relay sends more than I requested in `limit` I will close the connection. 

Your bostr instance at bostr.lecturify.net is one of the spammy ones.
I send `["REQ","5bd775e7-178b-4861-be69-9be4b26f094f",{"authors":["6e75f7972397ca3295e0f4ca0fbc6eb9cc79be85bafdd56bd378220ca8eee74e"],"kinds":[1,6],"since":1716316333,"until":1716553420,"limit":105}]` but I receive more than 105.
Pls fix :D

**Comment by Yonle** [comment]
This is expected to happen as the bouncer just keeps fetching any content that still passes the filtering. This is because the bouncer could not guarantee that it's getting the newer events.

Still. It notifies that the limit has been reached to the client via EOSE as you seen below:
![Screenshot_20240524-193542.png](https://github.com/Yonle/bostr/assets/63401712/8dae6a8f-7545-4fa7-a705-9c528b3b8867)

At this case, Even with `since` and `until` being set, I was actually expecting the client to close the subscription, But feel free to correct me if i need to improve this.

**Comment by dluvian** [comment]
Ok that's fair. I will adjust my onEOSE logic so these cases don't get marked as spam.
