### ISSUE TITLE
Idea integration with bostr?

### ISSUE THREAD

**Issue by bolzobrazil** [Yonle/bostr#24]
Hi would these ideas be integrateable with bostr?
https://github.com/nostr-protocol/nostr/issues/194
https://www.reddit.com/r/TOR/comments/1e4te8m/introducing_discussing_reflectors_as_concept/
https://lists.torproject.org/pipermail/tor-relays/2024-July/021744.htm

**Comment by Yonle** [comment]
Not really understand at this, However, Nostr relay is just dumb storage that store billions of event data blobs. Currently, the way of how the protocol works for purposes (posting, messaging, etc) was like this:

1. User connect to relay(s)
2. After connect, User open 1 subscription that request the relay to receive requested data blob. It could be messaging data.
3. To send a message / post (or stuff), User simply send the corresponding event data blob to relay, and then the relay says "OK". We could confirm that it's here by opening an subscription

As of this, This project is just an bouncer or an proxy. It follows what nostr does with NIP-01.

Because of that, I will close this issue until the further follow ups.
